name: habit_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  # animated_background: null
  # animated_text_kit: ^4.2.3
  # audioplayers: ^6.4.0
  # awesome_notifications: ^0.10.1
  cached_network_image: ^3.4.1
  # card_swiper: ^3.0.1
  # chewie: 1.8.1
  # circular_countdown_timer: null
  connectivity_plus: null
  country_code_picker: ^3.1.0
  cupertino_icons: ^1.0.8
  device_info_plus: null
  # draggable_bottom_sheet: ^1.0.2 # to remove this
  # fetch_client: 1.1.1
  # file_picker: ^8.1.6
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  # flutter_bounce: ^1.1.0
  flutter_html:
    git:
      url: https://github.com/appmeetmighty/flutter_html.git
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  # flutter_mobx: ^2.3.0
  # flutter_staggered_grid_view: ^0.7.0
  # flutter_time_picker_spinner: ^2.0.0
  # flutter_toggle_tab: 1.4.1
  # flutter_tts: ^4.0.2
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  # marquee: null
  # mobx: ^2.5.0
  path_provider: ^2.1.4
  # pedometer: ^4.0.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^5.0.1
  share_plus: ^10.0.0
  shared_preferences: ^2.5.2
  simple_pip_mode: ^0.8.0
  # syncfusion_flutter_charts: ^26.2.14
  # syncfusion_flutter_datepicker: ^26.2.13
  # table_calendar: ^3.1.2
  # top_snackbar_flutter: null
  # tuple: ^2.0.2
  url_launcher: ^6.3.0
  # video_player: ^2.9.2
  # youtube_player_flutter: null

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.5
  flutter_svg: ^1.0.0
  flutter_layout_grid: ^2.0.5
  webview_flutter: ^4.8.0
  fading_edge_scrollview: null

dev_dependencies:
  build_runner: ^2.4.11
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
