name: habit_tracker
description: A new Flutter project.

version: 1.0.0+1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter_local_notifications: ^14.0.0
  timezone: ^0.9.0
  cached_network_image: ^3.4.1
  connectivity_plus: null
  country_code_picker: ^3.1.0
  cupertino_icons: ^1.0.8
  device_info_plus: null
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_html:
    git:
      url: https://github.com/appmeetmighty/flutter_html.git
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_time_picker_spinner: ^2.0.0
  flutter_tts: ^4.0.2
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  path_provider: ^2.1.4
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^5.0.1
  share_plus: ^10.0.0
  shared_preferences: ^2.5.2
  simple_pip_mode: ^0.8.0
  syncfusion_flutter_charts: ^26.2.14
  syncfusion_flutter_datepicker: ^26.2.13
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  youtube_player_flutter: null

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.5
  flutter_svg: ^1.0.0
  flutter_layout_grid: ^2.0.5
  webview_flutter: ^4.8.0
  fading_edge_scrollview: null
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  flutter_bounce: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.11
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
